name = input("enter a name")
name2 = input("enter a name")
name3 = input("enter a name")
name4 = input("enter a name")
mat = input("enter a material")
mat2 = input("enter a material")
mat3 = input("enter a material")

print("There once were three little pigs. The first ")
print("pig was called " + name + " , the second was ")
print("called " + name2 + " and the third was called ")
print(" name3 + . The first house was made from ")
print(" + mat + . The second house was made ")
print("from " + mat2 + " . The third house was made ")
print("from " + mat3 + " . The big bad wolf was ")
print("called " + name4 + " . The big bad wolf blew ")
print("down the first two houses. He could not ")
print("destroy the third house made from bricks. ")
print("The pigs lived happily ever after.")